### ISSUE TITLE
Is there a difference between this & the tokipona.net transliterate tool?

### ISSUE THREAD

**Issue by nathgit** [dvtate/tokipona-japanese#1]
具去变え画言去画ニヨンり在[此](http://tokipona.net/tp/Transliterate.aspx)。
此り变ぴ此ぬ何？
新ら此り能作え画ソンコ。

ilo tawa ante e sitelen toki tawa sitelen NIJON li lon [ni](http://tokipona.net/tp/Transliterate.aspx).
ni li ante pi ni anu seme?
sin la ni li ken pali e sitelen SONKO

There is a transliterator to convert to Japanese characters [here](http://tokipona.net/tp/Transliterate.aspx).
Is it different from this?
It can also do Chinese characters.

**Comment by dvtate** [comment]
Hi, it seems that this program does the same thing as [this](http://tokipona.net/tp/Compress.aspx) but likely this one has more bugs. I might spend some time fixing them (they're pretty simple) next weekend (I need to study for midterms this one). Regardless I think the official tool is likely better than what I've made here.

**Comment by nathgit** [comment]
I don't mean to diminish what you made at all. I was just curious if there was a difference.
